Add string generation
Hellwest/obsidian-chest pull request #1
Opened 2020-07-30 05:26 UTC by Hellwest

2020-07-30 13:07 UTC, Orlha requested changes

2020-07-30 13:07 UTC, Orlha commented on os.h
> +#include <stdlib.h>
C++ project
```suggestion
#include <cstdlib>
```

2020-07-30 13:07 UTC, Orlha commented on os.h
> +		std::string result = "";
std::string class is empty-string initialized by default;
```suggestion
		std::string result;
```

2020-07-30 13:07 UTC, Orlha commented on os.h
> +		int i = 0;
Local variable definition could be moved to for-loop head;
```suggestion

```

2020-07-30 13:07 UTC, Orlha commented on os.h
> +		int randomNumber;
Local variable definition could be moved to for-loop head;
```suggestion
```

2020-07-30 13:07 UTC, Orlha commented on os.h
> +		for (i = 0; i < length; i++) {
```suggestion
		for (int i = 0; i < length; ++i) {
```

2020-07-30 13:07 UTC, Orlha commented on os.h
> +			randomNumber = std::rand() % 26;
```suggestion
			int randomNumber = std::rand() % 26;
```

2020-07-30 13:07 UTC, Orlha commented on os.h
> +			letter = 'a' + randomNumber;
```suggestion
			char letter = 'a' + randomNumber;
```

2020-07-30 13:07 UTC, Orlha commented on os.h
> +			result[i] = letter;
```suggestion
			result += letter;
```

2020-07-30 13:07 UTC, Orlha commented on main.cpp
> +
```suggestion
std::cout << result << "\n";
```

2020-07-30 13:16 UTC, Hellwest commented on os.h
> +namespace os {
`namespace oc {`

2020-07-30 13:16 UTC, Hellwest commented on main.cpp
> +#include "os.h"
`#include <os.h>`

2020-08-06 11:02 UTC, Orlha commented on .gitignore
> +*.out
When building via CMake, build generation and compilation processes are done in "build" folder, so further git-ignores are not necessary.

2020-08-06 11:02 UTC, Orlha commented on CMakeLists.txt
> +	oc.h
Headers are included, implementation is compiled.
```suggestion
	oc.cpp
```

2020-08-06 11:02 UTC, Orlha commented on oc.cpp
> +constexpr char OC::possible_chars[];
Not sure about the design choice here.
`constexpr static` in header should be enough.

2020-08-06 11:02 UTC, Orlha commented on oc.h
> +#include <chrono>
If an interface doesn't depend on these parts of library, they can be safely moved to an implementation file.

2020-10-05 15:59 UTC, merged